CICD: Fix deployment

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -29,9 +29,7 @@ jobs:
         with:
           context: ./frontend/
           push: true
-          tags: |
-            nabin011011/wanderlust-frontend:v1.0
-            nabin011011/wanderlust-frontend:latest
+          tags: nabin011011/wanderlust-frontend:latest
 
   backend-build:
     runs-on: ubuntu-latest
@@ -57,9 +55,7 @@ jobs:
         with:
           context: ./backend/
           push: true
-          tags: |
-            nabin011011/wanderlust-backend:v1.0
-            nabin011011/wanderlust-backend:latest
+          tags: nabin011011/wanderlust-backend:latest
 
   deploy:
     runs-on: ubuntu-latest
@@ -80,7 +76,7 @@ jobs:
           host: ${{ secrets.AWS_HOST }}
           username: ${{ secrets.AWS_USERNAME }}
           key: ${{ secrets.AWS_SSH_KEY }}
-          port: ${{ secrets.PORT }}
+          port: ${{ secrets.AWS_PORT }}
           source: "docker-compose.yaml"
           target: "/home/ubuntu/"
 
@@ -90,9 +86,16 @@ jobs:
           host: ${{ secrets.AWS_HOST }}
           username: ${{ secrets.AWS_USERNAME }}
           key: ${{ secrets.AWS_SSH_KEY }}
-          port: ${{ secrets.PORT }}
+          port: ${{ secrets.AWS_PORT }}
           script: |
+            set -e
+            sudo apt update
+            sudo apt install -y docker-compose
             cd /home/ubuntu/
-            sudo docker-compose pull
-            sudo docker-compose up -d
+            if [ ! -f docker-compose.yaml ]; then
+              echo "docker-compose.yaml not found!"
+              exit 1
+            fi
+            sudo docker-compose pull || { echo "Docker pull failed"; exit 1; }
+            sudo docker-compose up -d || { echo "Docker Compose failed"; exit 1; }
             sudo docker system prune -f
